### ISSUE TITLE
TypeScript section

### ISSUE THREAD

**Issue by DanielRosenwasser** [verekia/js-stack-from-scratch#50]
Hey there, this is a really great resource for people. I was wondering whether you'd be willing to take a PR for a section on TypeScript, since I noticed you also had a section on type-checking with Flow as well.

**Comment by verekia** [comment]
Hey! Thanks for the suggestion.

The thing is, it's not really Flow vs. Typescript, but Babel + Flow vs. Typescript, because of you go for Typescript you need to use their compiler as well.

What gives me mixed feelings about Typescript is that is has a more monolithic approach than Babel + plugins. The web moves so fast that you sometimes want to use some really brand new libraries, and I don't want to wait for the Typescript team to ship that feature months later and be blocked in the meantime. With Babel, if some guy has a Github repo of a really great Babel plugin with very few stars, you can still use it right away. It's exactly like comparing Sass (~ Typescript) and PostCSS (~ Babel + plugins), one has a more monolithic approach - which is great if you're doing common things, but the latter is more flexible and modular, which I find highly valuable in this fast-pace ecosystem.

I know there are a lot of people who use Typescript, but in the React community, it is much more leaned towards Babel, even though Typescript has JSX support. So Babel is more beginner friendly for newcomers who want to use React and find resources and support.

Regarding type checking in general, Flow is not necessarily better than Typescript, they are both great, and using any is already a great practice. The one that is best suited for this Babel / React stack is Flow in my opinion though.

**Comment by verekia** [comment]
Closing this :) Will revisit if the React community shifts towards TS in the future.

**Comment by stevestock** [comment]
+1 for having a Typescript section

**Comment by mhf-ir** [comment]
+1 for TypeScript

**Comment by lukemt** [comment]
Thank You for the explanation 👍  @verekia
