### ISSUE TITLE
Using a collaborative translation service

### ISSUE THREAD

**Issue by RaedsLab** [verekia/js-stack-from-scratch#58]
### Feature suggestion

I have noticed that a large number of the issues are relative to translation. 

Why not coordinate this in a cleaner way over something like [transifex](https://www.transifex.com/) ?

**Comment by verekia** [comment]
It might be tricky to use an other service than GitHub repos because we literally need translations to "fork" the main repo with the ability to merge its recent changes (as described [here](https://github.com/verekia/js-stack-from-scratch/blob/master/how-to-translate.md). Translations repos can potentially get really out of sync with the main one. I think it is actually a very clean workflow to use GitHub for that.

**Comment by xmalinov** [comment]
You can use the Crowdin. It's a very handy tool for translations managing.
If you're interested, look [here](https://github.com/thejameskyle/documentation-handbook/blob/master/CONTRIBUTING.md) for a tiny tutorial.

**Comment by verekia** [comment]
Closing this for now. I'm happy with the workflow we've been doing so far.
