### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by fellstroke** [verekia/js-stack-from-scratch#80]
### Question:
Are you sure about the linter? Because I've been writing JS for quite some time now, and I'm pretty sure that semicolons are not needed (just as an example).

**Comment by domino14** [comment]
Airbnb's eslint config enforces a coding style that requires semicolons (among many other things)

**Comment by verekia** [comment]
Well it's not that this is the wrong linter, since it is entirely configurable to fit your coding style. It's just that Airbnb prefers semicolons.

See this rule to customize ESLint: http://eslint.org/docs/rules/semi

I also omit semicolons in my own code, but it is still a relatively uncommon thing to do unfortunately. I plan to add an extra section at the end of the tutorial for those who want to get rid of semicolons.
